/**
 * Download the two web fonts (Poppins, Inter) into assets/fonts and write a
 * local @font-face stylesheet, so the landing never depends on a third-party
 * font CDN at runtime.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'fonts');
const OUT_CSS = path.join(ROOT, 'assets', 'fonts.css');

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Poppins:wght@600;700;800&display=swap';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`font css ${res.status}`);
  const css = await res.text();

  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
  const rules = [];
  let bytes = 0;

  for (const [, subset, body] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = /font-family:\s*'([^']+)'/.exec(body)[1];
    const weight = /font-weight:\s*(\d+)/.exec(body)[1];
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)[1];
    const range = /unicode-range:\s*([^;]+);/.exec(body)[1].trim();

    const file = `${family.toLowerCase()}-${weight}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, file), buf);
    bytes += buf.length;

    rules.push(
      [
        '@font-face {',
        `  font-family: '${family}';`,
        '  font-style: normal;',
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('fonts/${file}') format('woff2');`,
        `  unicode-range: ${range};`,
        '}',
      ].join('\n')
    );
  }

  fs.writeFileSync(
    OUT_CSS,
    `/* Generated by tools/fetch-fonts.js — self-hosted Poppins + Inter. */\n\n${rules.join('\n\n')}\n`
  );

  console.log(`${rules.length} font files, ${Math.round(bytes / 1024)} KB total`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
